### ISSUE TITLE
Handle upstream

### ISSUE THREAD

**Issue by axic** [wanderer/common#12]
I think upstream is kind of useless and should be deleted. Nobody uses it.

Additionally, this should be detached from upstream: https://stackoverflow.com/a/44140289

**Comment by axic** [comment]
Any comments, @holgerd77 ?

**Comment by holgerd77** [comment]
Yes, makes sense. Should we do this be repository recreation or through GitHub support? I have also no access the the ``ethereum`` org version.

**Comment by holgerd77** [comment]
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository

**Comment by holgerd77** [comment]
Maybe we should start by making https://github.com/ethereum/common private and see what happens?

**Comment by holgerd77** [comment]
Since these are both organization repos with various people having access, going through GitHub support "allowing" this is probably difficult.

**Comment by axic** [comment]
> one of the existing public forks is chosen to be the new parent repository

That doesn't seem anything useful :)

I think we could ask support to remove the link from `ethereumjs/common` and see what happens. Then it is a separate issue to delete `ethereum/common`, but that is outside the scope of ethereumjs.

**Comment by axic** [comment]
This repo was superseded by ethereumjs-common.
