### ISSUE TITLE
Update Ropsten bootstrap nodes

### ISSUE THREAD

**Issue by holgerd77** [wanderer/common#13]
The two Ropsten bootstrap nodes in ``bootstrapNodes.json`` both are unavailable, so Ropsten nodes should be updated.

See: https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go

**Comment by axic** [comment]
Closing this since this library is superseded by ethereumjs-common and it has been fixed there: https://github.com/ethereumjs/ethereumjs-common/pull/20
